import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const sora = Sora({
    variable: "--font-sora",
    subsets: ["latin"],
    weight: ["400", "500", "700"], // Add weights you need
});

export const metadata = {
    title: "BDB India",
    description: "Generated by create next app",
     icons: {
        icon: "/favicon.png", // Path from public folder
        shortcut: "/favicon.png",
        apple: "/favicon.png",
    },
};

export default function RootLayout({ children }) {
    return (
       <html lang="en" className="overflow-x-hidden">
      <body className={`max-w-[100vw] overflow-x-hidden ${sora.variable}`}>
        {children}
      </body>
    </html>
    );
}
